services:
  frontend:
    build:
      context: ./journalfrontend
    ports:
      - "3000:3000"
    networks:
      - "app-network"
    env_file:
      - .env
    environment:
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      NASA_API_KEY: ${NASA_API_KEY}

networks:
  app-network:
    driver: bridge
