services:
  frontend:
    build:
      context: ./journalfrontend
    ports:
      - "3000:3000"
    networks:
      - "app-network"
    env_file:
      - .env
    environment:
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      NASA_API_KEY: ${NASA_API_KEY}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}


  # backend:
  #   build:
  #     context: ./journalbackend
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network
  #   env_file:
  #     - .env
  #   environment:
  #     REDIS_HOST: redis    # Service name 'redis' defined in Docker Compose
  #     REDIS_PORT: 6379
  #     AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY}
  #     AWS_SECRET_KEY: ${AWS_SECRET_KEY}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_REGION: ${AWS_REGION}



  # redis:
  #   image: "redis:alpine"
  #   container_name: redis
  #   networks:
  #     - app-network
  #   ports:
  #     - "6379:6379"

networks:
  app-network:
    driver: bridge
